# Generated by Django 5.2.4 on 2025-07-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasback', '0002_userprofile_notification_preferences_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default=9999999999, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
